version: '2'
services:

  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: docker.io/bitnami/kafka:2
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
    depends_on:
      - zookeeper
    ports:
      - 9092:9092


networks:
  default:
    driver: bridge
